binarylogic/authlogic

- lib/authlogic/regex.rb
- test/acts_as_authentic_test/email_test.rb
Apparently ampersands are allowed in email addresses according to the RFC. This PR should allow for that.
> Allow ampersand in email per RFC 2822 3.2.4

- lib/authlogic/acts_as_authentic/login.rb
The case_sensitive_modifiier api has now changed and required 2 params in rails 4.2.
https://github.com/rails/rails/blob/03b304c88588737f55f58952cd6cbe356cd75a90/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L624
> Rails 4.2 support

- README.rdoc
- lib/authlogic/acts_as_authentic/email.rb
- lib/authlogic/i18n.rb
- lib/authlogic/regex.rb
- test/acts_as_authentic_test/email_test.rb
This is a simple but passable first draft regex for international email addresses. Given that the standard may be in flux, this simply emulates the original @email_regex but rather than allowing specific characters for each part, it instead disallows the complement set of characters.
Relevant to https://github.com/binarylogic/authlogic/issues/176#issuecomment-55828878
> Add Authlogic::Regex::email_nonascii

- README.rdoc
I believe Authlogic used to have a generator, but when that was removed there was no obvious example migration for newcomers (other than `test_helper.rb`). This makes it a little more obvious how to get setup with Authlogic.
> Add example migration to README

- test/session_test/cookies_test.rb
example test case(travis-ci)
https://travis-ci.org/binarylogic/authlogic/jobs/65079080
```
1) Failure:
SessionTest::CookiesTest::InstanceMethodsTest#test_after_save_save_cookie_with_remember_me [/home/travis/build/binarylogic/authlogic/test/session_test/cookies_test.rb:177]:
--- expected
+++ actual
@@ -1 +1 @@
-"6cde0674657a8a313ce952df979de2830309aa4c11ca65805dd00bfdc65dbcc2f5e36718660a1d2e68c1a08c276d996763985d2f06fd3d076eb7bc4d97b1e317::110237153::2015-09-02T13:39:37+00:00"
+"6cde0674657a8a313ce952df979de2830309aa4c11ca65805dd00bfdc65dbcc2f5e36718660a1d2e68c1a08c276d996763985d2f06fd3d076eb7bc4d97b1e317::110237153::2015-09-02T13:39:36+00:00"
```
> Fixed a possible failure test

- lib/authlogic/acts_as_authentic/login.rb
- lib/authlogic/i18n.rb
- test/acts_as_authentic_test/login_test.rb
`should use only letters, numbers, spaces, and .-_@ please.`  =>
`should use only letters, numbers, spaces, and .-_@+ please.`
> Fixes validation message for error_messages.login_invalid

- lib/authlogic/regex.rb
- test/acts_as_authentic_test/login_test.rb
* Modified regex
* Added test_validates_format_of_login_field
`/\A\w[\w\.+\-_@ ]+\z/` =>
`/\A[a-zA-Z0-9][a-zA-Z0-9\.+\-_@ ]+\z/`
```
$ ruby -cw lib/authlogic/regex.rb
lib/authlogic/regex.rb:44: warning: character class has duplicated range: /\A\w[\w\.+\-_@ ]+\z/
```
because `\w` is `[a-zA-Z0-0_]`. 
that is current regex has duplicated _(underscore).
By the way, I think to wrong initial character has allowed _(underscore) on regex.
So, Changes not allowed _(underscore) on initial character.
e.g. `u.login = "_underscore"`
before  `u.valid? # => true`
after `u.valid? # => false`
> Fixes regex for validate login

- authlogic.gemspec
scrypt 3 is backwards compatible with scrypt 2, there are no breaking changes.
- https://github.com/pbhogan/scrypt/blob/master/CHANGELOG.md
- https://github.com/pbhogan/scrypt/pull/57
> Allow scrypt 3

- CHANGELOG.md
- lib/authlogic/acts_as_authentic/password.rb
- test/acts_as_authentic_test/password_test.rb
- test/acts_as_authentic_test/session_maintenance_test.rb
Rebase of https://github.com/binarylogic/authlogic/pull/481
> Increased minimum password length from 4 to 8

- test/test_helper.rb
Fixes test warning
```
DEPRECATION WARNING: You did not specify a value for the configuration option `active_support.test_order`. In Rails 5, the default value of this option will change from `:sorted` to `:random`.
To disable this warning and keep the current behavior, you can add the following line to your `config/environments/test.rb`:
Rails.application.configure do
config.active_support.test_order = :sorted
end
Alternatively, you can opt into the future behavior by setting this option to `:random`. (called from test_order at /Users/naberon/work/gem/authlogic/vendor/bundler/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/test_case.rb:42)
```
> Fixes test warning for ActiveSupport.test_order option

- README.md
Open to other wording, suggestions on basic ways of addressing this issue. 
Fixes #310
> Adding note about CSRF protection to README.

- lib/authlogic/session/magic_columns.rb
Currently, if an application uses both `last_request_at_update_allowed?` and `last_request_at_threshold`, the former takes priority over the latter. If the controller returns true to `last_request_at_update_allowed?`, then `last_request_at` WILL be updated, even if it's within the threshold time period.
This patch updates this behavior so that `last_request_at` is not updated if `last_request_at_update_allowed?` is true OR if `last_request_at_threshold` has not been met.
> Fix conflict between last_request_at_update_allowed? and last_request_at_threshold

- .rubocop.yml
- .rubocop_todo.yml
- CONTRIBUTING.md
- Rakefile
- lib/authlogic/acts_as_authentic/password.rb
- lib/authlogic/acts_as_authentic/single_access_token.rb
- lib/authlogic/authenticates_many/base.rb
- lib/authlogic/crypto_providers/aes256.rb
- lib/authlogic/random.rb
- lib/authlogic/session/brute_force_protection.rb
- lib/authlogic/session/cookies.rb
- lib/authlogic/session/foundation.rb
- lib/authlogic/session/magic_states.rb
- lib/authlogic/session/params.rb
- lib/authlogic/session/password.rb
- lib/authlogic/session/scopes.rb
- lib/authlogic/session/session.rb
- test/acts_as_authentic_test/password_test.rb
- test/acts_as_authentic_test/session_maintenance_test.rb
- test/session_test/session_test.rb
The ruby style guide recommends a line length of 80, but that is quite strict. I go for 80 in new projects, but on existing projects I typically go for 100. This project has some extremely long method names, like `merge_validates_length_of_password_field_options`, so 100 may be too ambitious.
> Lint: Improve Metrics/LineLength to 140

- lib/authlogic/acts_as_authentic/login.rb
- test/acts_as_authentic_test/email_test.rb
- test/acts_as_authentic_test/login_test.rb
Login validation message will be rendered using the locale set at the time the validation is run rather than the locale at the time the file is booted.
> Fixes login validation message to respect the current locale

- .rubocop_todo.yml
- .travis.yml
- CHANGELOG.md
- authlogic.gemspec
- lib/authlogic/config.rb
- lib/authlogic/regex.rb
- test/acts_as_authentic_test/email_test.rb
According to the [2016 Rails Hosting Survey](http://rails-hosting.com/2016/index.html), usage of ruby 1.9.3 has dropped to around 10%, with much of this drop occuring in 2016.
> Usage of 1.9.3 dropped by 16% [since the 2015 survey] and adoption of Ruby 2.2 and 2.3 jumped up to 27% each.
The 2016 survey had 1,417 respondents.
IMO, it is acceptable for development of a new major version of authlogic, version 4, to continue, while the 10% of the community using 1.9.3 continues to use authlogic 3.
Semver does not specify how to treat this change, and there is no consensus that I'm aware of in the ruby community. I recommend a major version bump. Version numbers are free, after all.
> Drop support for ruby 1.9.3

- lib/authlogic/test_case.rb
Since 3.4.0, the default crypto_provider is SCrypt. The fixture example in the docs is configured with Sha512.
This will make fail any attempt to save the UserSession in test. In particular for rails 5, the login trick (https://github.com/rails/rails/issues/23386#issuecomment-192954569) will fail.
> Fix fixture example in testing docs

- .rubocop_todo.yml
- lib/authlogic/session/scopes.rb
Separates the *definition* of the scope from the *application* of
the scope.
As a secondary benefit, avoids assigning the result of a multiline
conditional, which I find hard to read.
> Extract private method #search_scope

- CHANGELOG.md
- lib/authlogic/session/cookies.rb
- test/session_test/cookies_test.rb
Re:  this discussion: https://github.com/binarylogic/authlogic/pull/524#issuecomment-261812813
I think it's time to set `httponly` and `secure` to `true` by default on Authlogic's remember-me cookie. 
* `secure` will ensure that the remember-me cookie is always sent while encrypted
* `httponly` will ensure that XSS attacks do not have access to the remember-me cookie
> Enable httponly and secure cookies by default now.

- CHANGELOG.md
- lib/authlogic/controller_adapters/abstract_adapter.rb
- test/adapter_test.rb
Authlogic's `controller` variable is [actually a RailsAdapter](https://github.com/binarylogic/authlogic/blob/master/lib/authlogic/controller_adapters/rails_adapter.rb#L57-L59) that proxies methods to the underlying controller.
Since the adapter has a `method_missing` that proxies anything to the controller, we should also make sure ~~`respond_to?`~~ `respond_to_missing?` is here too.
Example: someone could extend Authlogic and check `controller.respond_to?(:foo)`, and it would incorrectly return `false`, whilst they're still able to call `controller.foo` just fine.
> Add respond_to? alongside method_missing in the adapter classes.

- CHANGELOG.md
- README.md
- lib/authlogic/acts_as_authentic/session_maintenance.rb
- test/acts_as_authentic_test/session_maintenance_test.rb
Split the config option into two as per discussed in [522](https://github.com/binarylogic/authlogic/issues/522) - one for keeping the authentication on password update and another one for automatically log in a new user on creation.
```
acts_as_authentic do |c| 
c.automatically_log_in_new_user = true 
c.update_session_with_password_change = true 
end 
```
> Splitting maitain_sessions config into 2 options.

- lib/authlogic/acts_as_authentic/perishable_token.rb
- lib/authlogic/random.rb
- test/random_test.rb
Authlogic only supports rails >= 3.2 and ruby >= 2.1. Under those conditions, ruby's securerandom library is always available and rails' defunct securerandom library is never available. The latter was removed in rails 3.1.
> ✂️ Remove unreachable code in authlogic/random

- CHANGELOG.md
- lib/authlogic/random.rb
It was close, now it should be conforming slightly better.
As an added bonus, now it returns strings of a consistent length.
> Conform Random.friendly_token to RFC-4648

- CHANGELOG.md
- lib/authlogic/i18n.rb
- lib/authlogic/session/existence.rb
- test/session_test/existence_test.rb
From https://github.com/binarylogic/authlogic/issues/98
> Allow users to customize invalid session error message

- .travis.yml
- CHANGELOG.md
- authlogic.gemspec
- test/gemfiles/Gemfile.rails-5.1.x
Backport https://github.com/binarylogic/authlogic/pull/549 to the `3-stable` branch so we can cut a 3.6.0 release.
> Allow rails 5.1

- .travis.yml
- CHANGELOG.md
- authlogic.gemspec
- lib/authlogic/session/password.rb
`Array#wrap` is defined by activesupport >= 4.
Dang, I just realized we haven't decided whether to drop support for rails 3 yet. Well, I'll open a PR and we can discuss it. :)
Obviously I am not suggesting we drop rails < 4.2 just so I can use `Array.wrap`. The reason is because rails < 4.2 are EOL already.
> Use Array.wrap (Oh, and btw drop rails < 4.2 😱)

- CHANGELOG.md
- lib/authlogic/regex.rb
- test/acts_as_authentic_test/email_test.rb
This regex would fail if a user would use a tld larger than 12 characters, for example someuser@somedomain.travelersinsurance.  As such, increasing it to 24 characters to allow the ICANN domains listed here within their master list.
https://data.iana.org/TLD/tlds-alpha-by-domain.txt
> Allow max length of tld to 24 

- lib/authlogic/session/timeout.rb
Just a couple of quick corrections for the `logged_in_timeout` documentation.
> logged_in_timeout documentation fix

- .travis.yml
- CHANGELOG.md
- README.md
- authlogic.gemspec
Ruby 2.1 reached EoL on 2017-04-01
https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/
> Drop support for ruby 2.1

- lib/authlogic/session/password.rb
Fixes #512
What do you think? Should we have special code to deal with `ActionController::Parameters`?
We could fix #512 by adding even more special code, or we could simplify the whole thing by requiring a plain `Hash`. But, that's a breaking change.
> Deprecate ActionController::Parameters

- .travis.yml
- CHANGELOG.md
- README.md
- authlogic.gemspec
- test/gemfiles/Gemfile.rails-5.2.x
This PR relieves restrictions on activesupport and activerecord versions. As requested by @jaredbeck this PR targets master instead of `stable-3`.
> Allows support for Rails 5.2

- lib/authlogic.rb
- lib/authlogic/crypto_providers/aes256.rb
- lib/authlogic/session/password.rb
- test/test_helper.rb
Mostly just improving the explanation of AC:Parameters deprecation, but I also had to backport some test suite stuff from master to get my tests passing locally.
> Prepare for release 3.8.0

- CHANGELOG.md
- lib/authlogic/session/cookies.rb
- lib/authlogic/test_case/mock_cookie_jar.rb
- test/session_test/cookies_test.rb
Add ability to support cookies that set the SameSite flag to "Strict" or "Lax".
See spec:
https://tools.ietf.org/html/draft-west-first-party-cookies-07
See Rack support:
https://github.com/rack/rack/blob/master/test/spec_response.rb#L118
I leave the validation of setting a correct value to Rack.
> SameSite cookie support

- CHANGELOG.md
- lib/authlogic/acts_as_authentic/queries/find_with_case.rb
Hi there,
Updating the Authlogic gem this morning, I found myself stuck because of our CI running [bundler-audit](https://github.com/rubysec/bundler-audit).
It notably relies on RubyGem interface to make verifications, with things like [this](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/requirement.rb#L24) (please notice the `Gem::Version#bump` that modifies the underlying object here).
Long story short : `.dup` ActiveRecord gem version before freezing it (I went for the conservative solution but maybe we could let go of the `.dup.freeze` altogether).
Since freezing modifies the object in place, and since ActiveRecord.gem_version is a constant, doing so has repercussions outside the scope of Authlogic, which does not look like a desirable behavior.
For reference, I pinned …
> Dup ActiveRecord gem version before freezing it

- .rubocop.yml
- lib/authlogic/acts_as_authentic/email.rb
- lib/authlogic/acts_as_authentic/login.rb
- lib/authlogic/regex.rb
- test/acts_as_authentic_test/email_test.rb
1. Use x-mode regexes, which are much more readable than
the string interpolation we had been using.
2. They're constant, so make them constants
> Rewrite the Authlogic::Regex module

- lib/authlogic/crypto_providers.rb
- lib/authlogic/crypto_providers/wordpress.rb
- test/crypto_provider_test/wordpress_test.rb
See reasons given in comments and in deprecation warning message.
> Deprecate crypto_providers/wordpress.rb

- .rubocop.yml
- .rubocop_todo.yml
- CHANGELOG.md
- CONTRIBUTING.md
- lib/authlogic/acts_as_authentic/base.rb
- lib/authlogic/acts_as_authentic/password.rb
- lib/authlogic/acts_as_authentic/restful_authentication.rb
- lib/authlogic/session/password.rb
- test/acts_as_authentic_test/restful_authentication_test.rb
Also, various docs and linting.
`CryptoProviders::SHA1` is not deprecated, because it is very likely that people are still using it. They shouldn't use it, but we will probably continue to support SHA1 for a long time.
When we do eventually remove support for restful_authentication, some of the most complicated parts of `acts_as_authentic/password.rb` will be simpler.
> Deprecate support for restful_authentication

- lib/authlogic/acts_as_authentic/password.rb
- lib/authlogic/crypto_providers.rb
- lib/authlogic/crypto_providers/md5.rb
AES256, because it is reversible, seems like such a poor choice that I think we should deprecate it. WDYT?
MD5 and SHA-1 are also poor choices. We shouldn't deprecate them yet, because people might still be transitioning (`transition_from_crypto_providers`) but I think we should print a warning.
SHA-256 and SHA-512 are reasonable choices, and popular I bet, but I'd like to print a warning, recommending an adaptive algorithm instead. Too naggy?
In addition to the above questions, I'd welcome any corrections to my copy-writing, specifically where I attempt to describe vulnerabilities. To that end, I'll take the liberty of CC'ing @pbhogan and @stakach from scrypt, @tjschuck and @tenderlove from bcrypt. Thanks in advance for taking a look.
> Deprecate AES256, guide users to choose a better crypto provider

- lib/authlogic/authenticates_many/base.rb
In early 2017, when we discussed our "wishlists", Ben mentioned that
he would like to drop `authenticates_many`. At that time, I was using
it at work, but I am not using it any longer.
It's a useful feature, but I'd like to see Authlogic "core" do less.
As the message says, if someone wants to extract and maintain a
new gem, that'd be fine. I'd help someone get started with that.
> Deprecate authenticates_many

- lib/authlogic/acts_as_authentic/email.rb
- lib/authlogic/acts_as_authentic/login.rb
- lib/authlogic/acts_as_authentic/password.rb
- lib/authlogic/acts_as_authentic/validations_scope.rb
- lib/authlogic/config.rb
I don't understand why Authlogic has these features, when these validations
can be accomplished using normal ActiveRecord validations. 
**Maybe I'm missing something?**
In my own production apps I disable these and I use the normal AR validations.
> Deprecate unnecessary validation features

- authlogic.gemspec
- lib/authlogic/session/validation.rb
- test/session_test/validation_test.rb
A story in two acts
1. Drop rails 2 support in our session validation errors class
2. Now our subclass is exactly the same as its parent, ActiveModel::Errors, so just use the parent
> Session validation errors: Require ActiveModel

- .rubocop_todo.yml
- lib/authlogic/session/callbacks.rb
- lib/authlogic/session/existence.rb
- lib/authlogic/session/persistence.rb
- lib/authlogic/session/validation.rb
- test/session_test/callbacks_test.rb
Delete the methods named eg. `before_save`, `validate`, etc. which
were used to run callbacks. Instead, explicitly use `run_callbacks`.
It is very confusing to me to have two different methods named eg.
`before_save`.
1. The class method `before_save` is the "callback installation
method" (my term). This method uses `set_callback` to install a callback
for the eg. `:before_save` *event*.
2. The instance method `before_save` (which this commit deletes)
which just called `run_callbacks(:before_save)`
By deleting the later, we can now easily:
- distinguish "callback installation" from "callback running"
- search the codebase for all `run_callback` sites
This is not a breaking change. The deleted methods were private API.
As such, I don't think we should mention this in the changelog.
Even …
> Explicitly use run_callbacks

- CHANGELOG.md
- README.md
- doc/use_normal_rails_validation.md
- lib/authlogic/acts_as_authentic/password.rb
- lib/authlogic/acts_as_authentic/perishable_token.rb
- lib/authlogic/acts_as_authentic/persistence_token.rb
- lib/authlogic/acts_as_authentic/session_maintenance.rb
- lib/authlogic/acts_as_authentic/single_access_token.rb
- lib/authlogic/session/callbacks.rb
- test/acts_as_authentic_test/password_test.rb
- test/fixtures/admins.yml
- test/libs/admin.rb
- test/libs/admin_session.rb
- test/libs/user.rb
- test/test_helper.rb
In Rails 5.1, new methods were added that split dirty attribute tracking into _before_ save and _after_ save versions.  Before save, you have will_save_change_to_<attribute>? and in after save you have saved_change_to_<attribute>?, there are a lot of these methods and in Rails 5.2 the behavior of accessing a <attribute>_changed? method or <record>_changed? in an after callback is changed to be the opposite behavior of what it is now.  Rails 5.1 added deprecation warnings for these.
- replace calls to activemodel defined <attribute>_changed? and <attribute>_was?  methods with will_save_change_to_<attribute>? and <attribute_in_database>
Commit in Rails:
https://github.com/rails/rails/commit/16ae3db5a5c6a08383b974ae6c96faac5b4a3c81
> Address Rails 5.1 changes to ActiveModel::Dirty

- .rubocop.yml
- .rubocop_todo.yml
- CONTRIBUTING.md
- lib/authlogic/session/base.rb
Disable metrics cops in specific parts of file, instead of entire file.
> Stricter linting of metrics cops

- CHANGELOG.md
- lib/authlogic/session/base.rb
- test/session_test/cookies_test.rb
This is the type of problem that we didn't notice because `#credentials`
was split among different files. Now that it's all in one place, the problem
becomes obvious.
> Session::Base#credentials should always return hash

- lib/authlogic.rb
- lib/authlogic/cookie_credentials.rb
- lib/authlogic/session/base.rb
- No change to tests
- No change to public API
- In Session::Base, now we can say `creds.remember_me_until` instead
of saying `creds[2]`. This is clearly an improvement.
- Now we can easily unit-test CookieCredentials.
I think there's also a CookieManager waiting to be extracted ..
> Extract private class CookieCredentials

- .travis.yml
- Gemfile
- authlogic.gemspec
- gemfiles/rails_5.2.rb
- gemfiles/rails_6.0.rb
```
/home/travis/.rvm/gems/ruby-2.3.8/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem': Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile. (LoadError)
```
> Tests: Fix gem activation issue re: sqlite3

- gemfiles/rails_6.0.rb
- lib/authlogic/acts_as_authentic/queries/find_with_case.rb
After some change in API 
https://github.com/rails/rails/blob/e4213e7c682f2b4bf19383ea1af1681c81c96ac5/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb  we receive error
> Fix Rails case_insensitive_comparison change API

- CHANGELOG.md
- lib/authlogic/acts_as_authentic/perishable_token.rb
- lib/authlogic/acts_as_authentic/persistence_token.rb
- lib/authlogic/acts_as_authentic/single_access_token.rb
Fix DEPRECATION WARNING: Uniqueness validator will no longer enforce case sensitive comparison in Rails 6.1. To continue case sensitive comparison on the :persistence_token attribute in User model, pass `case_sensitive: true` option explicitly to the uniqueness validator.
> Fix deprecation warning with validates_uniqueness_of

- README.md
Fix links to headings 1.a and 1.b in README.md
> Fix internal links in README.md

- README.md
I was looking to update to rails 5.2 and wanted to check if this was
supported on the version 3 of the branch. According to
https://github.com/binarylogic/authlogic/pull/582
Rails 5.2 is supported now on Authlogic v 3, so, updating the table
accordingly.
Also updating the version identifiers to be <= 5.2 etc. as 5.3 doesn't
exist.
> Update table of activerecord versions supported.

- lib/authlogic/session/base.rb
The default value of `allow_http_basic_auth()` has been changed to false in #521, but the comments have not been updated yet.
> Update the comment for `Authlogic::Session::Base#allow_http_basic_auth`

- lib/authlogic/i18n/translator.rb
authlogic/lib/authlogic/i18n/translator.rb:11: warning: The last argument is used as the keyword parameter
Explicit kwargs with double splat to be ruby-2.7 ready
> Fix ruby 2.7 warning on kwargs changes:

- lib/authlogic/session/base.rb
While reading the relevant comment fixed by this PR, I had to pause and read it multiple times, before digging further in the source. This PR removes the ambiguity.
> Fix ambiguous comment.

- README.md
Hello
If you allow multiple emails for a user, you will not be able to make it unique when you login, causing problems.
I thought it would be better to explicitlv make it unique, but what about?
> email is unique in README

- CHANGELOG.md
The referenced list contains `XN--VERMGENSBERATUNG-PWB` which is 25 characters. The code seems correct and rates a 25 character tld as valid while 26 characters are invalid.
> Fix typo: longest allowed tld is 25 characters

- CHANGELOG.md
- README.md
- lib/authlogic/session/base.rb
- test/session_test/cookies_test.rb
Addresses #700 - Support for None as a valid SameSite attribute
> Add None as a valid SameSite attribute

- CHANGELOG.md
- lib/authlogic/session/base.rb
- lib/authlogic/test_case/mock_cookie_jar.rb
- test/session_test/cookies_test.rb
This is a redo of https://github.com/binarylogic/authlogic/pull/666 , porting the encrypted_cookies feature from Authlogic 4.4.
Better late than never!
> Forward-porting encrypted cookies in 5.2

- lib/authlogic/acts_as_authentic/session_maintenance.rb
"warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call"
Fixes #716
> Eliminate Ruby 2.7 warnings about keywords arguments usage.

- lib/authlogic/controller_adapters/rails_adapter.rb
- lib/authlogic/session/base.rb
- lib/authlogic/test_case.rb
- lib/authlogic/test_case/mock_api_controller.rb
- lib/authlogic/test_case/mock_controller.rb
- lib/authlogic/test_case/mock_request.rb
- test/adapter_test.rb
- test/session_test/persistence_test.rb
Because `ActionController::API` does not include `ActionController::Cookies` metal and `ActionDispatch::Cookies` rack module,
Therefore, our controller can not use the `cookies` method.
In this patch, `Authlogic::Session::Base` calls `controller#cookies` only when available.
> Use cookies only when available

- CHANGELOG.md
- lib/authlogic/acts_as_authentic/base.rb
- lib/authlogic/errors.rb
- test/acts_as_authentic_test/base_test.rb
Some Authlogic modules requires a database connection with a existing table by the moment when you call the `acts_as_authentic` method. Currently the errors are rescued and some modules will not be included to the User model. Rising a exception will prevent the load of User model without some Authlogic modules. 
If you rely on the User model load before the database is setup correctly (e.g. eager loading on rake tasks), you can disable the error with:
```
acts_as_authentic do |c|
c.raise_on_database_errors = false
end
```
Fixes #724
> Raise an error if database connection is not established before using acts_as_authentic

- lib/authlogic/session/base.rb
If you enable eager loading or try to use the `UserSession` model before the first request, `Authlogic::Session::Base.controller` is not initialized so if you set `sign_cookie` or `encrypt_cookie`, it will crash.
> Fix encrypt_cookie and sign_cookie when controller is nil

- CHANGELOG.md
- lib/authlogic/session/base.rb
Fixes https://github.com/binarylogic/authlogic/issues/726
> [Fix #726] Thread safety: Session::Base.klass_name

- CHANGELOG.md
- lib/authlogic/session/base.rb
- test/session_test/password_test.rb
`find_by_login_method` is deprecated in favor of `record_selection_method`, to avoid confusion with ActiveRecord's "Dynamic Finders". (https://guides.rubyonrails.org/v6.0/active_record_querying.html#dynamic-finders) For example, `rubocop-rails` is confused by the deprecated method. (https://github.com/rubocop-hq/rubocop-rails/blob/master/lib/rubocop/cop/rails/dynamic_find_by.rb)
> Deprecate find_by_login_method

- lib/authlogic/test_case/mock_cookie_jar.rb
- lib/authlogic/test_case/rails_request_adapter.rb
- test/adapter_test.rb
- test/session_test/cookies_test.rb
In Authlogic v6.2, a new method `cookie_enabled?` started exercising cookie code in test cases in a few more places than usual, resulting in existing test code in downstream projects that included cookies with [string values](https://api.rubyonrails.org/classes/ActionDispatch/Cookies.html) (rather than hash values) to start failing with:
```
TypeError: no implicit conversion of Symbol into Integer
```
This PR adds support for both, using the same approach as [Rails itself](https://github.com/rails/rails/blob/71bc41477da96bb05edc33c1b6a42203e6999667/actionpack/lib/action_dispatch/middleware/cookies.rb#L364-L370).
Before:
After:
> Support string cookie values in rails test cases

- .rubocop_todo.yml
- CONTRIBUTING.md
- lib/authlogic/session/base.rb
This is in regard to Issue [742](https://github.com/binarylogic/authlogic/issues/742).
This is a proposal for how to solve the deprecation warning mentioned the issue, and is not ready to be merged.
The test suite runs fine for this PR for Rails 5.2, 6.0, 6.1 and 7.0.
> Proposed solution for ActiveRecord deprecation in Rails 7.0

- gemfiles/rails_7.0.rb
- lib/authlogic/session/base.rb
- test/acts_as_authentic_test/perishable_token_test.rb
- test/session_test/brute_force_protection_test.rb
This pull request has two changes:
1. Change the Rails 7 version to call 7.0.0.rc1.
2. Fix the underlying code to avoid a `default_timezone` depreciation warning.
All comments / questions welcome.
> Check against rails 7 0 rc1

- CHANGELOG.md
- authlogic.gemspec
There's a [new feature in Rubygems](https://guides.rubygems.org/mfa-requirement-opt-in/) that lets you require MFA on privileged gem operations by setting metadata in your gemspec. Once this is pushed to Rubygems, it will enforce this flag.
It would also display the requirement on the gem page, e.g.:
> Add gemspec flag that requires MFA for gem privileged operations.

- .github/workflows/test.yml
- authlogic.gemspec
- lib/authlogic.rb
- lib/authlogic/acts_as_authentic/base.rb
- lib/authlogic/acts_as_authentic/login.rb
- lib/authlogic/i18n.rb
- lib/authlogic/test_case.rb
- lib/authlogic/version.rb
This PR loads authlogic once Active Record has successfully loaded. It fixes an issue around eager loading in Rails 8 (possibly earlier versions too).
Closes https://github.com/binarylogic/authlogic/issues/776
Closes https://github.com/binarylogic/authlogic/issues/774
Fixes https://github.com/binarylogic/authlogic/issues/458
> Load authlogic at the proper time
