binarylogic/authlogic

CHANGELOG.md, authlogic.gemspec
Scrypt changelog: https://github.com/pbhogan/scrypt/blob/master/CHANGELOG.md
=> Allow scrypt 2.x

lib/authlogic/acts_as_authentic/password.rb
=> fix reset_password when disabled password_confirmation

lib/authlogic/session/magic_states.rb
`Has the record been conirmed?` =>
`Has the record been confirmed?`
=> Fixes typo

lib/authlogic/acts_as_authentic/email.rb, lib/authlogic/acts_as_authentic/password.rb, lib/authlogic/authenticates_many/base.rb, lib/authlogic/crypto_providers/aes256.rb, lib/authlogic/i18n.rb, lib/authlogic/session/base.rb, lib/authlogic/session/brute_force_protection.rb, lib/authlogic/session/callbacks.rb, lib/authlogic/session/cookies.rb, lib/authlogic/session/existence.rb, lib/authlogic/session/password.rb, lib/authlogic/session/scopes.rb, lib/authlogic/session/timeout.rb, lib/authlogic/test_case.rb
Found and fixed some typos in the code comments.
=> Fixed typos.

.travis.yml
https://docs.travis-ci.com/user/migrating-from-legacy/
=> Use container-based CI, supposedly faster

.gitignore, .travis.yml, CHANGELOG.md, authlogic.gemspec, lib/authlogic/acts_as_authentic/login.rb, lib/authlogic/session/callbacks.rb, lib/authlogic/session/password.rb, test/acts_as_authentic_test/logged_in_status_test.rb, test/acts_as_authentic_test/password_test.rb, test/gemfiles/Gemfile.rails-3.2.x, test/gemfiles/Gemfile.rails-5.0.x, test/session_test/active_record_trickery_test.rb, test/test_helper.rb
Fix for callbacks in rails 5 #484
=> Rails 5 callback

.rubocop.yml, .rubocop_todo.yml, CONTRIBUTING.md, lib/authlogic/acts_as_authentic/base.rb, lib/authlogic/acts_as_authentic/email.rb, lib/authlogic/acts_as_authentic/login.rb, lib/authlogic/acts_as_authentic/password.rb, lib/authlogic/acts_as_authentic/session_maintenance.rb, lib/authlogic/crypto_providers/bcrypt.rb, lib/authlogic/crypto_providers/scrypt.rb, lib/authlogic/session/brute_force_protection.rb, lib/authlogic/session/cookies.rb, lib/authlogic/session/params.rb, lib/authlogic/session/timeout.rb, test/acts_as_authentic_test/email_test.rb, test/acts_as_authentic_test/perishable_token_test.rb, test/session_test/existence_test.rb, test/session_test/http_auth_test.rb, test/session_test/magic_columns_test.rb, test/session_test/perishability_test.rb, test/session_test/session_test.rb
More (still conservative) linting. 
I will squash these if CI passes.
=> Linting tuesday

lib/authlogic/acts_as_authentic/login.rb
A simple fix for [issue #508](https://github.com/binarylogic/authlogic/issues/508).
=> Fixing case sensitivity bug for Rails/Activerecord 5.0

README.md, test/acts_as_authentic_test/session_maintenance_test.rb, test/session_test/brute_force_protection_test.rb, test/session_test/existence_test.rb, test/session_test/magic_columns_test.rb, test/session_test/magic_states_test.rb, test/session_test/perishability_test.rb, test/session_test/timeout_test.rb, test/test_helper.rb
Various improvements to docs and tests. See commit messages for details. 
My preference would be to keep these commits separate, not squash.
=> Various docs and tests

lib/authlogic/acts_as_authentic/password.rb
@binarylogic and/or @tiegz please review; security-related.
Simplifies `password_valid?` by extracting a private method,
`encryptor_matches?`.
The fact that one method, `encrypt_arguments`, prepares an array
of arguments to be splatted into another method, `encryptor.matches?`
remains a design issue, IMO.
Maybe there should be an object that acts as an intermediary between
the `Password` module and the various crypto providers.
Finally, the feature which supports an easy transition from
`restful_authentication` indroduces an immense amount of complexity.
> Simplicity is a prerequisite for reliability.
> -Dijkstra
This is security-related code. It needs to be reliable. We may want
to consider removing some features here.
=> Refactor password matching logic

lib/authlogic/test_case.rb
Here's the pull request to go along with issue #489.
=> Adds documentation for testing in Rails 5

CHANGELOG.md, lib/authlogic/session/http_auth.rb, test/acts_as_authentic_test/persistence_token_test.rb, test/session_test/cookies_test.rb, test/session_test/http_auth_test.rb, test/session_test/persistence_test.rb
Changeset for https://github.com/binarylogic/authlogic/issues/520
=> Change http auth from opt-out to opt-in.

.rubocop.yml, .rubocop_todo.yml, lib/authlogic.rb, lib/authlogic/acts_as_authentic/base.rb, lib/authlogic/acts_as_authentic/login.rb, lib/authlogic/acts_as_authentic/password.rb, lib/authlogic/acts_as_authentic/persistence_token.rb, lib/authlogic/crypto_providers/wordpress.rb, lib/authlogic/random.rb, lib/authlogic/session/activation.rb, lib/authlogic/session/active_record_trickery.rb, lib/authlogic/session/callbacks.rb, lib/authlogic/session/cookies.rb, lib/authlogic/session/existence.rb, lib/authlogic/session/password.rb, lib/authlogic/session/scopes.rb, lib/authlogic/test_case/mock_controller.rb, lib/authlogic/test_case/mock_cookie_jar.rb, test/i18n_test.rb, test/test_helper.rb
This concludes the fixing of the most serious category of linter offenses, the "Lint" category. (Less serious offenses are referred to as "Style" offenses).
These offenses (in the "Lint" category) are described as ".. possible errors and very bad practices .." (http://rubocop.readthedocs.io/en/latest/cops/) and are a higher priority than "Style" offenses, so I am happy to present the last of them, fixed.
=> Linting, various

.rubocop_todo.yml, test/acts_as_authentic_test/login_test.rb
- Organize a big test method into two methods
- Organize a big TestCase class into two classes
=> Organize login_test.rb

.rubocop.yml, .rubocop_todo.yml, authlogic.gemspec, lib/authlogic/acts_as_authentic/base.rb, lib/authlogic/acts_as_authentic/email.rb, lib/authlogic/acts_as_authentic/password.rb, lib/authlogic/crypto_providers/aes256.rb, lib/authlogic/crypto_providers/sha1.rb, lib/authlogic/regex.rb, lib/authlogic/session/activation.rb, lib/authlogic/session/brute_force_protection.rb, lib/authlogic/session/callbacks.rb, lib/authlogic/session/cookies.rb, lib/authlogic/session/magic_columns.rb, lib/authlogic/session/session.rb, lib/authlogic/test_case.rb, lib/authlogic/test_case/mock_controller.rb, lib/authlogic/test_case/mock_request.rb, lib/authlogic/test_case/rails_request_adapter.rb, test/acts_as_authentic_test/login_test.rb, test/acts_as_authentic_test/password_test.rb, test/acts_as_authentic_test/perishable_token_test.rb, test/random_test.rb, test/session_test/active_record_trickery_test.rb, test/test_helper.rb
Now that we've fixed the most serious linter offenses (https://github.com/binarylogic/authlogic/pull/525) we can turn our attention to style and metrics.
=> Lint 2016-12-02

CHANGELOG.md, README.md, UPGRADING.md
📄 🎄 📄 🎄 📄 🎄 📄 🎄 📄 🎄 🎅 
- Add a Table of Contents
- Add links to old readmes
- Add a compatibility table
- Organize badges
- Move upgrading instructions to UPGRADING.md
[ci skip]
=> All I want for xmas is docs

.travis.yml, authlogic.gemspec, test/gemfiles/Gemfile.rails-3.2.x, test/gemfiles/Gemfile.rails-4.0.x, test/gemfiles/Gemfile.rails-4.1.x, test/gemfiles/Gemfile.rails-4.2.x, test/gemfiles/Gemfile.rails-5.0.x, test/gemfiles/Gemfile.rails-master
=> Compatibility work 2017-02-18

.travis.yml, authlogic.gemspec, test/gemfiles/Gemfile.rails-5.1.x
The tests pass, so .. :shipit:
=> Allow rails 5.1

README.md
=> 548: remember_me doesn't work in chrome.

CONTRIBUTING.md, test/gemfiles/Gemfile.rails-3.2.x, test/gemfiles/Gemfile.rails-4.0.x, test/gemfiles/Gemfile.rails-4.1.x
We don't support these versions of rails anymore.
=> Delete defunct gemfiles

.gitignore, .travis.yml, CHANGELOG.md, authlogic.gemspec, lib/authlogic/crypto_providers/aes256.rb, test/test_helper.rb
Get CI passing against ruby 2.4
=> Test ruby 2.4

CHANGELOG.md, lib/authlogic/session/foundation.rb, lib/authlogic/session/password.rb, test/session_test/foundation_test.rb
Notable prior discussions:
- https://github.com/binarylogic/authlogic/issues/512
- https://github.com/binarylogic/authlogic/pull/558
- https://github.com/binarylogic/authlogic/pull/577
=> Remove support for ActionController::Parameters

.travis.yml, authlogic.gemspec, test/gemfiles/Gemfile.rails-5.2.x
Backports Rails 5.2 compatibility to version 3 of the gem.
=> Allows Rails 5.2 on version 3

.rubocop_todo.yml, lib/authlogic/acts_as_authentic/base.rb, lib/authlogic/acts_as_authentic/email.rb, lib/authlogic/acts_as_authentic/login.rb, lib/authlogic/acts_as_authentic/password.rb, lib/authlogic/acts_as_authentic/queries/find_with_case.rb, lib/authlogic/acts_as_authentic/restful_authentication.rb, lib/authlogic/controller_adapters/abstract_adapter.rb, lib/authlogic/controller_adapters/rack_adapter.rb, lib/authlogic/crypto_providers/sha256.rb, lib/authlogic/i18n.rb, lib/authlogic/session/active_record_trickery.rb, lib/authlogic/session/existence.rb, lib/authlogic/session/http_auth.rb, lib/authlogic/session/klass.rb, lib/authlogic/session/magic_states.rb, lib/authlogic/session/params.rb, lib/authlogic/session/persistence.rb, lib/authlogic/session/priority_record.rb, test/acts_as_authentic_test/password_test.rb, test/session_test/params_test.rb, test/test_helper.rb
The goal of this PR is to improve `Metrics/LineLength` from 120 to 110.
To achieve this, it was convenient to extract some private methods, and in one case, a new class.
A review focused on the newly extracted methods and class would be appreciated, but IMO not strictly necessary.
=> Linting 2018-02-13

CHANGELOG.md, CONTRIBUTING.md, authlogic.gemspec, lib/authlogic/version.rb, test/test_helper.rb
=> Release 4.0.0

Rakefile, authlogic.gemspec, lib/authlogic/acts_as_authentic/password.rb, lib/authlogic/session/id.rb, lib/authlogic/session/password.rb, lib/authlogic/test_case.rb, test/test_helper.rb
Fixing interpreter warnings about undefined instance variables
Continues Victor's work in https://github.com/binarylogic/authlogic/pull/604
=> Undefined ivar

UPGRADING.md, authlogic.gemspec, lib/authlogic.rb, lib/authlogic/acts_as_authentic/password.rb, lib/authlogic/acts_as_authentic/restful_authentication.rb, lib/authlogic/crypto_providers.rb, lib/authlogic/crypto_providers/aes256.rb, lib/authlogic/crypto_providers/sha1.rb, lib/authlogic/crypto_providers/sha512.rb, lib/authlogic/session/callbacks.rb, lib/authlogic/session/http_auth.rb, lib/authlogic/session/magic_columns.rb, lib/authlogic/session/magic_states.rb, lib/authlogic/session/params.rb, lib/authlogic/session/password.rb, lib/authlogic/session/session.rb
- update dev deps
- docs
- code style
=> Various 2018-07-10

.gitignore, .rubocop.yml, .travis.yml, Gemfile, gemfiles/Gemfile.rails-4.2.x, gemfiles/Gemfile.rails-5.1.x, gemfiles/Gemfile.rails-5.2.x, test/gemfiles/Gemfile.rails-4.2.x, test/gemfiles/Gemfile.rails-5.0.x, test/gemfiles/Gemfile.rails-master
It reached EoL this spring (2018) IIRC
=> Stop testing rails 5.0, it is EoL

test/test_helper.rb
On my laptop, this speeds up our test suite from 36s to 4s
=> Make our test suite 7x faster ⚡️

README.md
=> Docs: moved compatibility

README.md, authlogic.gemspec
- I'd like the tagline to mention ActiveRecord, since it is our
heaviest runtime dependency by far.
- Less important: I'd rather not say "clean, simple" because
no mature gem is clean and simple. I just spent a few hours figuring
out how PriorityRecord works, for example. Check out [the description
I just wrote in `priority_record.rb`](https://github.com/binarylogic/authlogic/commit/76e07e858fdf7a2084645c77c403d24f9807c2da). I'm not trying to put Authlogic
down, I just don't think any mature gem should claim to be "clean
and simple". Maybe I'm overthinking it, or have the wrong perspective
after having just worked with something objectively messy and complex.
- I definitely want to keep "unobtrusive" though. I think Authlogic lives
up to that claim. Unlike other solutions, we don't try to …
=> Proposed: New gem tagline

.travis.yml, CHANGELOG.md, README.md, authlogic.gemspec, gemfiles/Gemfile.rails-5.1.x, gemfiles/Gemfile.rails-6.0.x
We are trying to test our application on rails 6.0.0.alpha but we can't install this because of the version lock
Probably this will be helpful that we can try and report any issues with edge rails
=> Update upper dependency for actionpack

lib/authlogic/acts_as_authentic/password.rb
Rebasing Tieg's work from
https://github.com/binarylogic/authlogic/pull/420
@tiegz I tried to rebase your PR https://github.com/binarylogic/authlogic/pull/420 but the conflict was too much for me 😅
=> Update the way that callbacks are added to the model

lib/authlogic/acts_as_authentic/queries/find_with_case.rb, test/acts_as_authentic_test/login_test.rb, test/libs/user.rb
Fixes https://github.com/binarylogic/authlogic/issues/654
=> Fix ARel bug in FindWithCase

CHANGELOG.md
=> changelog entry for #659

README.md
Fixes #675.
Please let me know if the proposed changes to the paragraph describing `acts_as_authentic` is acceptable.
The change also includes a minor fix of the code snippet for `class ApplicationController`.
=> Docs: Update acts_as_authentic desc in README

README.md
=> Docs on session callbacks

lib/authlogic/controller_adapters/rails_adapter.rb
=> Lazily set up Rails controller adapter

authlogic.gemspec, gemfiles/rails_6.0.rb
Since Rails6 was officially released, so I updated the test target Rails version to that.
=> Update test target version of Rails6

test/test_helper.rb
https://github.com/colszowka/simplecov#getting-started
> 2. Load and launch SimpleCov at the very top of your `test/test_helper.rb`
> **Note:** If SimpleCov starts after your application code is already loaded (via require),
> it won't be able to track your files and their coverage!
=> Fixup the SimpleCov configuration for measurement test coverage.

CHANGELOG.md, README.md, lib/authlogic/session/cookies.rb, test/session_test/cookies_test.rb
=> Add None as a valid attribute to SameSite

CHANGELOG.md, lib/authlogic/errors.rb
Hi, just found a typo during the update process.
=> Fix a typo

lib/authlogic/session/base.rb
=> Fix increment_login_count typo

CHANGELOG.md, lib/authlogic/test_case/mock_cookie_jar.rb
=> String cookies followup

CHANGELOG.md, lib/authlogic/controller_adapters/abstract_adapter.rb, lib/authlogic/session/base.rb, lib/authlogic/test_case/mock_request.rb, test/session_test/password_test.rb, test/session_test/session_test.rb, test/test_helper.rb
Adds config option `session_fixation_defense` (default: true)
=> Defend against Session Fixation attack
